services:
  frontend:
    image: julieraymonddev/runalliance-front:latest
    restart: always
    ports:
      - "8081:80"
    deploy:
      resources:
        reservations:
          cpus: '0.3'
          memory: 576M
