version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4201:4200"
    networks:
      - run-alliance-network
    environment:
      - NODE_ENV=development

networks:
  run-alliance-network:
    external: true
